// <auto-generated />
using ControleAcessoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleAcessoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleAcessoApi.Models.Acesso", b =>
                {
                    b.Property<int>("AcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcessoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcessoId");

                    b.ToTable("Acessos");
                });

            modelBuilder.Entity("ControleAcessoApi.Models.UsuarioAcesso", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("AcessoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "AcessoId");

                    b.HasIndex("AcessoId");

                    b.ToTable("UsuarioAcessos");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControleAcessoApi.Models.UsuarioAcesso", b =>
                {
                    b.HasOne("ControleAcessoApi.Models.Acesso", "Acesso")
                        .WithMany("UsuarioAcessos")
                        .HasForeignKey("AcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Usuario", "Usuario")
                        .WithMany("UsuarioAcessos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acesso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleAcessoApi.Models.Acesso", b =>
                {
                    b.Navigation("UsuarioAcessos");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("UsuarioAcessos");
                });
#pragma warning restore 612, 618
        }
    }
}
